apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: oke-gateway
  namespace: default
  annotations:
    # OCI specific annotation for Network Load Balancer (Layer 4)
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
{%- if tls == "new_http_01" %}
  - name: https
    port: 443
    protocol: HTTPS
    hostname: ##TF_VAR_dns_name##
    tls:
      mode: Terminate
      certificateRefs:
      - name: ##TF_VAR_prefix##-tls-secret
{%- endif %}        