apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
  namespace: default
spec:
  compartmentId: "##TF_VAR_compartment_ocid##"
  subnetId: "##OKE_LB_SUBNET_OCID##"
  loadBalancerName: "##TF_VAR_prefix##-oke-lb"
  isPrivate: false
  maxBandwidthMbps: 50
  minBandwidthMbps: 10
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: default
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: native-ic-params