# Need Full docker image to have access to dnf 
FROM oraclelinux:8

WORKDIR /app
COPY src/wa_php_oci.sh /app
RUN  /app/wa_php_oci.sh && \
     {%- if db_family == "psql" %}
     yum install -y php-pgsql && \
     {%- endif %}     
     sed -i "s/Listen 80$/Listen 8080/" /etc/httpd/conf/httpd.conf && \
     rm /etc/nginx/default.d/php.conf 

  
# Set error_log and access_log to stout/stderr
RUN  sed -i 's#ErrorLog "logs/error_log"#ErrorLog /dev/stderr#g' /etc/httpd/conf/httpd.conf && \
     sed -i 's#CustomLog "logs/access_log"#CustomLog /dev/stdout#g' /etc/httpd/conf/httpd.conf && \
{%- if db_family == "container_instance" %}
# Comment listen.acl_users for Container Instance  
RUN  sed -i 's/apache,nginx/root/g' /etc/php-fpm.d/www.conf && \
     sed -i 's/^;listen.acl_groups =/listen.acl_groups = root/g' /etc/php-fpm.d/www.conf
{%- endif %}     

# sed -i 's/^listen.acl_users/;listen.acl_users/g' /etc/php-fpm.d/www.conf

WORKDIR /app
COPY src/html/* /var/www/html/
COPY src/php.ini.append.docker /app
RUN cat /app/php.ini.append.docker >> /etc/php.ini
COPY src/app.conf /etc/httpd/conf.d/
# ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
# Docker does not start php-fpm as service for strange reasons...
CMD ["/bin/bash", "-c", "mkdir /run/php-fpm && php-fpm && httpd -D FOREGROUND"]