FROM oraclelinux:7-slim

RUN  yum -y install oracle-release-el7 oracle-php-release-el7 && \
     yum-config-manager --disable ol7_developer_EPEL && \
     yum install -y php php-json && \
     {%- if db_family == "oracle" %}
     yum install -y oracle-instantclient-basic oracle-instantclient-sqlplus php-oci8-19c && \
     {%- elif db_family == "mysql" %}
     yum install -y php-mysql && \
     {%- elif db_family == "psql" %}
     yum install -y php-pgsql && \
     {%- endif %}     
     rm -rf /var/cache/yum && \
     sed -i "s/Listen 80$/Listen 8080/" /etc/httpd/conf/httpd.conf 

WORKDIR /app
COPY src/html/* /var/www/html/
COPY src/php.ini.append.docker /app
RUN cat /app/php.ini.append.docker >> /etc/php.ini
COPY src/app.conf /etc/httpd/conf.d/
ENTRYPOINT ["httpd", "-D", "FOREGROUND"]


yum install -y oracle-instantclient19.10-basic oracle-instantclient19.10-sqlplus
oracle-instantclient19.10-basic
oracle-instantclient19.10