-- DROP TABLE DEPT;
CREATE TABLE DEPT
       (DEPTNO INT PRIMARY KEY,
        DNAME VARCHAR(64),
        LOC VARCHAR(64) );

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH',   'POSTGRESQL');
INSERT INTO DEPT VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');
