-- DROP TABLE scott.dept ;
CREATE TABLE scott.dept 
       (DEPTNO INT PRIMARY KEY,
        DNAME VARCHAR(64),
        LOC VARCHAR(64) );

INSERT INTO scott.dept  VALUES (10, 'ACCOUNTING', 'TOKYO');
INSERT INTO scott.dept  VALUES (20, 'RESEARCH',   'POSTGRESQL');
INSERT INTO scott.dept  VALUES (30, 'SALES',      'BEIJING');
INSERT INTO scott.dept  VALUES (40, 'OPERATIONS', 'SEOUL');
