worker_processes  auto;

error_log  /tmp/error.log notice;
pid        /tmp/nginx.pid;


events {
    worker_connections  1024;
}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
        
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /tmp/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen 8080;
        listen [::]:8080;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = /ready {
            default_type application/json;
            add_header Cache-Control "no-store" always;
            return 200 '{"status":"ok","endpoint":"ready"}';
        }

        location = /health {
            default_type application/json;
            add_header Cache-Control "no-store" always;
            return 200 '{"status":"ok","endpoint":"health"}';
        }

        location / {
            try_files $uri $uri/ =404;
        }

        location /app/ {
            proxy_pass https://inference.generativeai.eu-frankfurt-1.oci.oraclecloud.com/20251112/hostedApplications/ocid1.generativeaihostedapplication.oc1.eu-frankfurt-1.amaaaaaa2xxap7ya762627vksltadb3acl77dfjfsjthxije3escy4vxkkdq/actions/invoke/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    include /etc/nginx/conf.d/*.conf;
}

